### ISSUE TITLE
boot.img not being created.

### ISSUE THREAD

**Issue by ghost** [luk1337/ext4_to_f2fs#1]
```
The file is already fully retrieved; nothing to do.
```

Disabling further reuse of socket 5.
Closed 5/SSL 0x0000000001d3a280
8608 blocks
error: failed writing '.rom/boot.img': Bad address
  adding: file_contexts (deflated 78%)
  adding: system/ (stored 0%)
  adding: system/framework/ (stored 0%)
  adding: system/framework/com.android.location.provider.jar (deflated 2%)
  adding: system/framework/framework.jar (deflated 1%)
  adding: system/framework/android.test.runner.jar (deflated 0%)

**Comment by luk1337** [comment]
Fixed
Commit: https://github.com/luk1337/ext4_to_f2fs/commit/86450aaf7c1eef92b5eb34c1eff3122ff4fd22f0
