### ISSUE TITLE
boot.img not being created.

### ISSUE THREAD

**Issue by ghost** [luk1337/ext4_to_f2fs#2]
2014-09-18 01:19:47 (251 KB/s) - ‘boot/ramdisk/sbin/busybox’ saved [1668176/1668176]

5279 blocks
usage: mkbootimg
       --kernel <filename>
       --ramdisk <filename>
       [ --second <2ndbootloader-filename> ]
       [ --cmdline <kernel-commandline> ]
       [ --board <boardname> ]
       [ --base <address> ]
       [ --pagesize <pagesize> ]
       [ --ramdisk_offset <address> ]
       [ --dt <filename> ]
       -o|--output <filename>
  adding: file_contexts (deflated 78%)
  adding: system/ (stored 0%)

**Comment by ghost** [comment]
just using the boot.img that came with your cm11 port with beastaki23's cm11 M10 rom, works, quite honestly this convertor has never worked for me on DirtyUnicorns, Resurection Remix, Miui v5, pac,aosb. I'm on s2 plus.

**Comment by luk1337** [comment]
Finally fixed: https://github.com/luk1337/ext4_to_f2fs/commit/ea278ac753026e6a1ed062db14d524788fdfd4f1
