### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by ghost** [luk1337/ext4_to_f2fs#3]
Any plans to implement lollipop support ? if not how to do it my self, links ?

**Comment by luk1337** [comment]
No plans since I have moto G 2014 now.

**Comment by ghost** [comment]
Nice, other than the 5" screen and huge battery capacity, what is so good about it ? 
So then how can I do it my self ? the patch fails, do I have to add f2fs support to the source code or do I just need to modify the boot image ? one other unrelated thing, is it possible to create a log  or some way to view the logcat via adb when the phone gets stuck on the "Samsung  Galaxy S II Plus" screen ? thank you, I was wondering why your posts suddenly stopped on the s2plus threads.

**Comment by luk1337** [comment]
Snapdragon = good support.
Don't know what's wrong, I'm not going to investigate that.

**Comment by ghost** [comment]
I would like to investigate it myself and possibly create a lollipop compatible version, thats why all the questions;
 "do I have to add f2fs support to the source code or do I just need to modify the boot image ? one other unrelated thing, is it possible to create a log or some way to view the logcat via adb when the phone gets stuck on the "Samsung Galaxy S II Plus" screen ?"

**Comment by luk1337** [comment]
You need to replace kernel and fstab.

**Comment by ghost** [comment]
okay, how then "is it possible to create a log or some way to view the logcat via adb when the phone gets stuck on the "Samsung Galaxy S II Plus" screen ?" how do I debug the problem in this case ?

**Comment by luk1337** [comment]
No you can't.

**Comment by ghost** [comment]
So its hit & miss ? do moshkernel & nebula need your patches & automount scripts ?

**Comment by ghost** [comment]
point me in the right direction, give me something.
